### ISSUE TITLE
Create Room: Default Name des Raums

### ISSUE THREAD

**Issue by danielschleindlsperger** [danielschleindlsperger/syncify#9]
Beim "From existing Playlist"-Flow sollte der Default-Name des Raums vermutlich der Name der Playlist sein. Macht die kognitive Belastung weg, sich was auszudenken. Außer man will das natürlich.

**Comment by Lynbarry** [comment]
Das würd ich mir mal anschauen!

**Comment by Lynbarry** [comment]
Ich fände das generell schon praktisch, hab's mir z.B. grad auch gewünscht als ich einen Raum erstellt habe.

Damit das Sinn macht müsste man aber eigentlich immer wenn die Playlist gewechselt wird den aktuell gesetzten Namen überschreiben. Oder man müsste sobald der Nutzer einmal etwas eingetippt hat ab dem Moment das überschreiben aussetzen. Aber das ist glaube ich auch kein wirklich leicht verständliches UX...

**Comment by danielschleindlsperger** [comment]
Ja, seh ich genauso! Wir dürfen auf keinen Fall den User Input überschreiben, es soll ja eher ein Vorschlag sein.

Meine Idee ist irgendwann eigentlich so ne Art Wizard:
1.  Wähle Quelle für die Playlist aus: Von existierender Playlist, manuell picken, von Genre, Spotify vorgefertigte Playlisten
2. Step Implementierung
3. Raum Details: Name, listed oder nicht, etc
4. Feuer frei

Dann hätte man das Problem mit dem Überschreiben nicht, weil man ja einfach ganz am Schluss ein vorausgefülltes Textfeld hat

**Comment by Lynbarry** [comment]
Stimmt ja. Vielleicht sollten wir als erstes diese 2-Step-Erstellung einbauen. Auch jetzt mit nur der einen Quelle.

Wir könnten dann im ersten Screen, bei der Auswahl der Playlist noch die enthaltenen Lieder anzeigen, das fände ich eigentlich ganz praktisch um zu sehen ob das wirklich die ist die ich wollte.

**Comment by danielschleindlsperger** [comment]
Hab ich hier mitgemacht: 630418f849e7377e7dd681d957db8a3d58adaf0c

Passt das?
